start: node_clause+

node_clause: NODE_NAME "{"  contract+  "}"

contract: "{" TOPIC ";" TYPE ";" GUARANTEE "}"

NODE_NAME: LETTER+
TOPIC: LETTER+
TYPE: LETTER+


GUARANTEE: LETTER+


%import common.LETTER
%import common.INT -> NUMBER
%import common.WS
%ignore WS
